#!/bin/bash
sudo rm /usr/local/bin/hoststool # generated by install.sh
sudo launchctl unload -w /Library/LaunchDaemons/hoststool.plist
sudo rm /Library/LaunchDaemons/hoststool.plist # generated by install.sh
sudo rm /etc/hosts.backup # generated by hoststool
sudo rm -rf /etc/hoststool # generated by hoststool in launchdaemon
sudo rm -rf $HOME/etc/hoststool # generated by hoststool in staff group
sudo rm -r $HOME/etc >/dev/null 2>&1 # remove folder if empty
sudo rm /Library/Logs/hoststool.log # generated by system launchDaemons
echo "[INFO] Totally uninstalled. Bye" 